name: my_flutter
description: my_flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  flutter_riverpod: ^0.12.4
  provider: ^4.3.3
  bloc: ^6.1.1
  flutter_bloc: ^6.1.2
  meta: ^1.2.4
  uuid: ^2.2.2
  equatable: ^1.2.6
  authentication_repository:
    path: lib/blocs/login/packages/authentication_repository
  user_repository:
    path: lib/blocs/login/packages/user_repository
  formz: ^0.3.2
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.4
  flutter_portal: ^0.3.0
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  freezed: ^0.12.7

flutter:
  uses-material-design: false

  fonts:
  - family: SourceSansPro
    fonts:
      - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
      - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
        weight: 700
  - family: SourceSansProLight
    fonts:
      - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Light.ttf
        weight: 300